#!/bin/bash

# Cronify v1 - job report wrapper
# Copyright 2012 Matthew Fallshaw. No rights reserved, whatsoever.
# Public Domain CC0: http://creativecommons.org/publicdomain/zero/1.0/
# evolved from Cronic - http://habilis.net/cronic/

set -eu

OUT=/tmp/cronify.out.$$
ERR=/tmp/cronify.err.$$
TRACE=/tmp/cronify.trace.$$
MSG=/tmp/cronify.msg.$$

set +e
"$@" >$OUT 2>$TRACE
RESULT=$?
set -e

PATTERN="^\\${PS4:0:1}+${PS4:1}"
if [ -s "$TRACE" ] && grep -aq "$PATTERN" $TRACE
then
    ! grep -av "$PATTERN" $TRACE > $ERR
else
    ERR=$TRACE
fi
cat $OUT

if [ $RESULT -ne 0 -o -s "$ERR" ]
then

  # remove part of error message caused by this script
  STR=`cat $TRACE`
  echo ${STR##*cronify: line [0-9][0-9]: } >$TRACE

  cat $ERR >&2
  echo "Cronify detected failure or error output for the command:" > $MSG
  echo "$@" >> $MSG
  echo >> $MSG
  echo "RESULT CODE: $RESULT" >> $MSG
  echo >> $MSG
  echo "ERROR OUTPUT:" >> $MSG
  cat "$ERR" >> $MSG
  echo >> $MSG
  echo "STANDARD OUTPUT:" >> $MSG
  cat "$OUT" >> $MSG
  if [ $TRACE != $ERR ]
  then
    echo >> $MSG
    echo "TRACE-ERROR OUTPUT:" >> $MSG
    cat "$TRACE" >> $MSG
  fi
  cat $MSG | mail -s "Cronify <`whoami`@`hostname`> $@" `whoami`
fi

rm -f "$OUT"
rm -f "$ERR"
rm -f "$TRACE"
rm -f "$MSG"
