#!/bin/bash

# Cronify v1 - job report wrapper
# Copyright 2012-2018 Matthew Fallshaw. No rights reserved, whatsoever.
# Public Domain CC0: http://creativecommons.org/publicdomain/zero/1.0/
# evolved from Cronic - http://habilis.net/cronic/

set -eu

TMP=$(mktemp -d)
OUT=$TMP/cronify.out
ERR=$TMP/cronify.err
TRACE=$TMP/cronify.trace
MSG=$TMP/cronify.msg.$$

set +e
"$@" >$OUT 2>$TRACE
RESULT=$?
set -e

PATTERN="^${PS4:0:1}\\+${PS4:1}"
if grep -aq "$PATTERN" $TRACE
then
    ! grep -av "$PATTERN" $TRACE > $ERR
else
    ERR=$TRACE
fi

if [ $RESULT -ne 0 -o -s "$ERR" ]
then
  (
  echo "Cronify detected failure or error output for the command:"
  echo "$@"
  echo
  echo "RESULT CODE: $RESULT"
  echo
  echo "ERROR OUTPUT:"
  cat "$ERR"
  echo
  echo "STANDARD OUTPUT:"
  cat "$OUT"
  if [ $TRACE != $ERR ]
  then
    echo
    echo "TRACE-ERROR OUTPUT:"
    cat "$TRACE"
  fi
  ) >$MSG
  cat $MSG
  cat $MSG | mail -s "Cronify <`whoami`@`hostname`> $@" `whoami`
fi

rm -rf "$TMP"
